global:
  scrape_interval: 720m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 720m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: 
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'web'
    scrape_interval: 720m
    static_configs:
      - targets: ['web:8000']

